/** Enums */

export enum AlertTypes {
  SUCCESS = 'success',
  INFO = 'info',
  WARNING = 'warning',
  DANGER = 'danger',
  SECONDARY = 'secondary',
  PRIMARY = 'primary',
  LIGHT = 'light',
  DARK = 'dark',
}

export enum StoreKeys {
  USER_FIELDS = 'USER_FIELDS',
  LOCATION_PREFERENCES = 'LOCATION_PREFERENCES',
}

export enum USER_RECORDS {
  // common
  FIELDS = 'fields',
  CONNECTIONS = 'connections',
  CONNECTION_REQUESTS = 'connection-requests',
  RESOURCES = 'resources',
  RESOURCE_INTERESTS = 'resource-interests',
  NOTIFICATIONS = 'notifications',
  FOLLOWERS = 'followers',
  FOLLOWINGS = 'followings',
  
  //hotspot
  POSTS = 'posts',
  CLIQUES = 'cliques',
  CLIQUE_INTERESTS = 'clique-interests',
  CLIQUE_MEMBERSHIPS = 'clique-memberships',
  CLIQUE_MEMBERSHIP_REQUESTS = 'member-requests',
  
  
  // deliverme
  DELIVERIES = 'deliveries',
  DELIVERINGS = 'deliverings',
  
  //travellrs
  MARKERS = 'markers',
  
  // world news



  // my favors
  FAVORS = 'favors',
  FAVOR_HELPINGS_ACTIVE = 'favor-helpings-active',
  FAVOR_HELPINGS_PAST = 'favor-helpings-past',


  
  // chef city
  RECIPES = 'recipes',
}

export enum MODERN_APPS {
  COMMON = 'common',
  HOTSPOT = 'hotspot',
  DELIVERME = 'deliverme',
  TRAVELLRS = 'travellrs',
  WORLDNEWS = 'worldnews',
  MYFAVORS = 'myfavors',
}

export enum REACTIONS {
  LIKE = 1,
  DISLIKE,
  LOVE,
  CLAP,
  IDEA,
  CONFUSED,
  EXCITED,
  CARE,
  LAUGH,
  WOW,
  SAD,
  UPSET,
  FIRE,
  ONE_HUNDRED,
}

export enum REACTION_TYPES {
  LIKE = 'LIKE',
  DISLIKE = 'DISLIKE',
  LOVE = 'LOVE',
  CLAP = 'CLAP',
  IDEA = 'IDEA',
  CONFUSED = 'CONFUSED',
  EXCITED = 'EXCITED',
  CARE = 'CARE',
  LAUGH = 'LAUGH',
  WOW = 'WOW',
  SAD = 'SAD',
  UPSET = 'UPSET',
  FIRE = 'FIRE',
  ONE_HUNDRED = 'ONE_HUNDRED',
}

export enum EVENT_TYPES {

  // socket actions
  SOCKET_TRACK = 'SOCKET_TRACK',
  SOCKET_TO_USER_EVENT = 'SOCKET_TO_USER_EVENT',
  SOCKET_JOIN_ROOM = 'SOCKET_JOIN_ROOM',
  SOCKET_LEAVE_ROOM = 'SOCKET_LEAVE_ROOM',

  // events
  NEW_MESSAGE = 'NEW_MESSAGE',
  NEW_MESSAGING = 'NEW_MESSAGING',
  NEW_MESSAGING_REQUEST = 'NEW_MESSAGING_REQUEST',
  MESSAGING_EVENTS_SUBSCRIBED = 'MESSAGING_EVENTS_SUBSCRIBED',
  MESSAGING_EVENTS_UNSUBSCRIBED = 'MESSAGING_EVENTS_UNSUBSCRIBED',

  NEW_TRACKER = 'NEW_TRACKER',
  NEW_TRACKER_REQUEST = 'NEW_TRACKER_REQUEST',
  NEW_TRACKER_REQUEST_CANCELED = 'NEW_TRACKER_REQUEST_CANCELED',
  NEW_TRACKER_REQUEST_ACCEPTED = 'NEW_TRACKER_REQUEST_ACCEPTED',
  NEW_TRACKER_REQUEST_REJECTED = 'NEW_TRACKER_REQUEST_REJECTED',
  STOP_TRACKING = 'STOP_TRACKING',
  STOP_TRACKER = 'STOP_TRACKER',
  
  NEW_CONVERSATION = 'NEW_CONVERSATION',
  NEW_CONVERSATION_MESSAGE = 'NEW_CONVERSATION_MESSAGE',
  CONVERSATION_MEMBER_REQUESTED = 'CONVERSATION_MEMBER_REQUESTED',
  CONVERSATION_MEMBER_REQUEST_CANCELED = 'CONVERSATION_MEMBER_REQUEST_CANCELED',
  CONVERSATION_MEMBER_REQUEST_ACCEPTED = 'CONVERSATION_MEMBER_REQUEST_ACCEPTED',
  CONVERSATION_MEMBER_REQUEST_REJECTED = 'CONVERSATION_MEMBER_REQUEST_REJECTED',
  CONVERSATION_MEMBER_ADDED = 'CONVERSATION_MEMBER_ADDED',
  CONVERSATION_MEMBER_REMOVED = 'CONVERSATION_MEMBER_REMOVED',
  CONVERSATION_MEMBER_LEFT = 'CONVERSATION_MEMBER_LEFT',
  CONVERSATION_EVENTS_SUBSCRIBED = 'CONVERSATION_EVENTS_SUBSCRIBED',
  CONVERSATION_EVENTS_UNSUBSCRIBED = 'CONVERSATION_EVENTS_UNSUBSCRIBED',
  CONVERSATION_MESSAGE_TYPING = 'CONVERSATION_MESSAGE_TYPING',
  CONVERSATION_MESSAGE_TYPING_STOPPED = 'CONVERSATION_MESSAGE_TYPING_STOPPED',
  CONVERSATION_UPDATED = 'CONVERSATION_UPDATED',
  CONVERSATION_DELETED = 'CONVERSATION_DELETED',

  NEW_WATCH = 'NEW_WATCH',
  NEW_WATCH_MESSAGE = 'NEW_WATCH_MESSAGE',
  WATCH_MEMBER_REQUESTED = 'WATCH_MEMBER_REQUESTED',
  WATCH_MEMBER_REQUEST_CANCELED = 'WATCH_MEMBER_REQUEST_CANCELED',
  WATCH_MEMBER_REQUEST_ACCEPTED = 'WATCH_MEMBER_REQUEST_ACCEPTED',
  WATCH_MEMBER_REQUEST_REJECTED = 'WATCH_MEMBER_REQUEST_REJECTED',
  WATCH_MEMBER_ADDED = 'WATCH_MEMBER_ADDED',
  WATCH_MEMBER_REMOVED = 'WATCH_MEMBER_REMOVED',
  WATCH_MEMBER_LEFT = 'WATCH_MEMBER_LEFT',
  WATCH_EVENTS_SUBSCRIBED = 'WATCH_EVENTS_SUBSCRIBED',
  WATCH_EVENTS_UNSUBSCRIBED = 'WATCH_EVENTS_UNSUBSCRIBED',
  WATCH_MESSAGE_TYPING = 'WATCH_MESSAGE_TYPING',
  WATCH_MESSAGE_TYPING_STOPPED = 'WATCH_MESSAGE_TYPING_STOPPED',
  WATCH_UPDATED = 'WATCH_UPDATED',
  WATCH_DELETED = 'WATCH_DELETED',

  NEW_PULSE = 'NEW_PULSE',
  NEW_PHOTO_PULSE = 'NEW_PHOTO_PULSE',
  NEW_CHECKPOINT = 'NEW_CHECKPOINT',
  NEW_CHECKPOINT_RESPONSE = 'NEW_CHECKPOINT_RESPONSE',
  NEW_USER_LOCATION_UPDATE = 'NEW_USER_LOCATION_UPDATE',
  
  TO_MESSAGING_ROOM = 'TO_MESSAGING_ROOM',
  JOIN_TO_MESSAGING_ROOM = 'JOIN_TO_MESSAGING_ROOM',
  LEAVE_TO_MESSAGING_ROOM = 'LEAVE_TO_MESSAGING_ROOM',
  MESSAGE_TYPING = 'MESSAGE_TYPING',
  MESSAGE_TYPING_STOPPED = 'MESSAGE_TYPING_STOPPED',
  
}

export enum NOTIFICATION_TARGET_TYPES {
  USER = 'USER',
  MESSAGING = 'MESSAGING',
  MESSAGE = 'MESSAGE',
  CONVERSATION = 'CONVERSATION',
  PULSE = 'PULSE',
  PHOTO_PULSE = 'PHOTO_PULSE',
  TRACKING = 'TRACKING',
  WATCH = 'WATCH',
  CHECKPOINT = 'CHECKPOINT',
}

export enum PULSE_CODES {
  // generic
  OKAY = 'OKAY',
  WARNING = 'WARNING',
  IN_DANGER = 'IN_DANGER',

  // okay
  REACHED_HOME_SAFE = 'REACHED_HOME_SAFE',
  REACHED_DESTINATION_SAFE = 'REACHED_DESTINATION_SAFE',

  // warning
  UNKNOWN_AREA = 'UNKOWN_AREA',
  PHONE_NEAR_DEAD = 'PHONE_NEAR_DEAD',
  FEELS_UNSAFE = 'FEELS_UNSAFE',
  OUTSIDE_ALONE = 'OUTSIDE_ALONE',

  // danger
  ABUSER_NEARBY = 'ABUSER_NEARBY',
  BEING_STALKED = 'BEING_STALKED',
  BEING_FOLLOWED = 'BEING_FOLLOWED',
  APPROACHED_BY_STRANGER = 'APPROACHED_BY_STRANGER',
  HARASSED_BY_STRANGER = 'HARASSED_BY_STRANGER',
}

export const STATUSES =  Object.freeze({
  PENDING: null,
  CANCEL: 2,
  ACCEPT: 1,
  REJECT: 0
})